# This is a basic workflow to help you get started with Actions
name: Deploy CDK
on:
  push:
    branches: 
      - develop
  
  pull_request:
    branches:
      - main
    types: 
      - closed

jobs:
  aws_cdk:
    if :github.event.pull_request.merged == true || github.even == "push":
      runs_on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-note@v2
        with:
          node-version: '18'
        
      - name: Install Dependecies
        run: npm install
        
      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: {{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CDK deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: '*'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
